## NumPy


- NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.
- NumPy library is written in C & C++ for efficiently performing operations on data which is represented in multi-dimensional arrays.
- By default in Python the data is managed as object which can not be always memory & processing efficient.
- The NumPy library can be installed using following command
- For Anaconda: conda install numpy
- For others (from console): pip install numpy
- Various operations as given below can be performed. 
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. 
- NumPy has in-built functions for linear algebra and random number generation
- NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). This combination is widely used as a replacement for MatLab.
- After installing the numpy can be imported as: import numpy as np

### Import NumPy
- Once NumPy is installed, import it in your applications by adding the import keyword:

In [1]:
import numpy
arr1 = numpy.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


### NumPy as np
- NumPy is usually imported under the np alias.

In [2]:
import numpy as np
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


## Checking NumPy Version
- The version string is stored under __version__ attribute.

In [1]:
import numpy as np
print(np.__version__)

1.20.1


### NumPy Creating Arrays
- NumPy is used to work with arrays efficiently. The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.

In [30]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
print(arr1)
print(type(arr1))
a=5
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>
<class 'int'>


- type(): This function is used to find the type of the objects passed to an array. Like in above code it shows that arr is numpy.ndarray type.
- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [34]:
import numpy as np
arr = np.array((1, 2, 3, 4, 128),np.int16)
print(arr)
print(type(arr))
print(arr.dtype)

[  1   2   3   4 128]
<class 'numpy.ndarray'>
int16


## numpy.array() in Python
- It is basically a table of elements which are all of the same type and indexed by a tuple of positive integers. The dimensions are called axis in NumPy.

### Dimensions in Arrays
#### 0-D Arrays
- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [37]:
import numpy as np
arr1 = np.array(42)
print(arr1)
print(arr1.dtype)

42
int32


### 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [45]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr[0])


['1' '2' '3' '4' '5']
1


### 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[1][1])
print(arr[0])

[[1 2 3]
 [4 5 6]]
5
[1 2 3]


In [5]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr[0])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]


### Check Number of Dimensions

In [48]:

import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
print(arr[0][0][0][0][0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1


## NumPy Array Indexing or accessing elements

In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[-4])
print(arr[1])
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[1][1])
print('2nd element on 1st dim: ', arr[1, 1])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 2])

1
2
2nd element on 1st dim:  7
2nd element on 1st dim:  7
12


In [13]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[-2, -2])

Last element from 2nd dim:  4


### NumPy Array Slicing
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 6 5 4 3 2]


In [15]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [22]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)

[[1 2 3 4 5]]


In [24]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### NumPy Data Types
- NumPy supports a much greater variety of numerical types than Python does. The following table shows different scalar data types defined in NumPy.

1	bool_

Boolean (True or False) stored as a byte

2	int_

Default integer type (same as C long; normally either int64 or int32)

3	intc

Identical to C int (normally int32 or int64)

4	intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5	int8

Byte (-128 to 127)

6	int16

Integer (-32768 to 32767)

7	int32

Integer (-2147483648 to 2147483647)

8	int64

Integer (-9223372036854775808 to 9223372036854775807)

9	uint8

Unsigned integer (0 to 255)

10	uint16

Unsigned integer (0 to 65535)

11	uint32

Unsigned integer (0 to 4294967295)

12	uint64

Unsigned integer (0 to 18446744073709551615)

13	float_

Shorthand for float64

14	float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15	float32

Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16	float64

Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17	complex_

Shorthand for complex128

18	complex64

Complex number, represented by two 32-bit floats (real and imaginary components)

19	complex128

Complex number, represented by two 64-bit floats (real and imaginary components)

- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [19]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherryyio'])
print(arr.dtype)

<U9


### Creating Arrays With a Defined Data Type

In [68]:
import numpy as np
arr = np.array([1, 23, 3, 4], dtype='S')
print(arr)
print(arr[0])
print(arr.dtype)

[b'1' b'23' b'3' b'4']
b'1'
|S2


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 128], dtype='i1')
print(arr)
print(arr.dtype)

[   1    2    3 -128]
int8


In [1]:
## In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
import numpy as np
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Type on Existing Arrays
- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [70]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
[ True False  True]
bool


### Copy vs View of an array
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
- Chance in copy is not reflected in original array while in view they are reflected

In [71]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42
print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]


In [72]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Get Shape of an Array

In [73]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
arr1 = np.array([1, 2, 3, 4], ndmin=5)
print(arr1)
print('shape of array :', arr1.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### Reshaping arrays

In [27]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
newarr3d = arr.reshape(2, 3, 2)
print(newarr3d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Array Iterating

In [75]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [76]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [77]:
## Iterate on each scalar element of the 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [78]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [80]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()
- The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In [30]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### Iterating Array With Different Data Types
- We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
- NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [31]:
import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
      print(x)

b'1'
b'2'
b'3'


## Iterating With Different Step Size

In [82]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, 0:3:2]):
      print(x)

1
3
5
7


## Joining Array
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [35]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2),axis=0)
print(arr)

[1 2 3 4 5 6]


In [37]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting NumPy Arrays

In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 5)
print(newarr)
print(newarr[0])
print(newarr[1])

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]
[1 2]
[3]


In [90]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [91]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [40]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]


### Searching Arrays
- To search an array, use the where() method.
- It returns an array of index of matched values

In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [93]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


### Search Sorted
- There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [51]:
import numpy as np
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

4


In [95]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right') ## to serach from right
print(x)

2


In [49]:
#Multiple Values Search
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


### Sorting Arrays

In [96]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [97]:
import numpy as np
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [98]:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [99]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Generate Random Number

In [100]:
#generate integer
from numpy import random
x = random.randint(100)
print(x)

17


In [101]:
# generate float from 0 to 1
from numpy import random
x = random.rand()
print(x)

0.2797089198747482


In [102]:
# Generate random array
from numpy import random
x=random.randint(100, size=(5))
print(x)

[85 16 53 88 56]


In [103]:
# Generate random 2D array
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[20 18 15  5  7]
 [36 49 95 40 26]
 [43 42 22 49 24]]


In [ ]:
## Generate Random Number From Array

In [104]:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

9


In [105]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 9 3 5 5]
 [5 9 9 7 7]
 [9 5 9 9 5]]


In [106]:
import numpy as np
myarr=np.array([3,4,5,6], np.int8)
print(myarr)

[3 4 5 6]


In [107]:
list1=[1,2,3,4,6,7,8,9]
list2=[3,4,5,6,7,8,9,10]
list3=[3,4,5,6,7,8,9,10]
myarr1=np.array([list1,list2,list3], np.int8)
print(myarr1)

[[ 1  2  3  4  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]]


In [108]:
arr=np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [109]:
rng=np.arange(2,13,3)
print(rng)

[ 2  5  8 11]


In [110]:
lspace=np.linspace(0,100,10)
print(lspace)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [111]:
## Creating an uninitialized array of given size 
emp=np.empty((4,6))
print(emp)

[[1.07843158e-311 7.26276499e-322 0.00000000e+000 0.00000000e+000
  1.33511018e-306 1.16095484e-028]
 [8.44747281e+252 7.23796664e+159 9.29846505e+242 1.33733641e+160
  6.19319847e-071 1.05161522e-153]
 [1.05194010e-153 1.14920486e+141 2.19993088e-152 5.28595687e-085
  1.07406561e+160 2.03534632e-028]
 [4.08135623e+223 8.29655075e-114 8.93168689e+271 4.98131536e+151
  1.94920670e-153 1.94920670e-153]]


Array Attributes

ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [112]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


In [113]:
import numpy as np 
tup1=(1,2,3,4)
tup2=(3,4,5,6)
a = np.array([tup1,tup2]) 
print(a)
print(a.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [114]:
import numpy as np 
str1="abcd"
str2="xyzl"
t=tuple(str1)
print(t)
a = np.array([tuple(str1),tuple(str2)]) 
print(a)
print(a.shape)

('a', 'b', 'c', 'd')
[['a' 'b' 'c' 'd']
 ['x' 'y' 'z' 'l']]
(2, 4)


### For more help access NumPy documentation
https://numpy.org/doc/stable/